<a href="https://colab.research.google.com/github/gcoelho3008/regressao_polinomial/blob/main/regressao_poli.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
! mkdir dados

In [7]:
! mv *csv dados

In [11]:
df_salario = pd.read_csv('./dados/salario.csv')

In [12]:
df_salario.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   tempo_na_empresa  1000 non-null   int64
 1   nivel_na_empresa  1000 non-null   int64
 2   salario_em_reais  1000 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 23.6 KB

In [13]:
# Copiar DF para DF EDA
df_salario_eda = df_salario.copy()

In [14]:
# copiar DF para DF Bucket
df_salario_bucket = df_salario.copy()

EDA

In [15]:
# Visualizar os dados
df_salario_eda.head(10)

   tempo_na_empresa  nivel_na_empresa  salario_em_reais
0                50                 1           2288.13
1                49                 4           2389.84
2                39                10           2158.73
3                51                 1           2341.06
4                62                 7           3584.20
5               105                10          12102.18
6                80                 3           5723.35
7                85                 2           6424.92
8                66                 5           3916.18
9                73                 5           4751.79

In [16]:
# detectar salários ausentes
df_salario_eda.isna().sum()

tempo_na_empresa    0
nivel_na_empresa    0
salario_em_reais    0
dtype: int64

In [17]:
# Medidas estatísticas DF
df_salario_eda.describe()

       tempo_na_empresa  nivel_na_empresa  salario_em_reais
count       1000.000000       1000.000000       1000.000000
mean          59.712000          5.467000       5093.726110
std           34.027679          2.889509       4536.168857
min            1.000000          1.000000        538.560000
25%           30.750000          3.000000       1537.477500
50%           60.000000          6.000000       3237.920000
75%           89.000000          8.000000       7436.680000
max          120.000000         10.000000      18923.230000